config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  resources :users, only: [:index, :show] do
    resources :relationships, only: :index
  end
  resources :songs
  resources :comments, except: [:index, :new, :show]
  resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reports, only: [:new, :create]

  namespace :admins do
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :destroy]
    resources :reports, only: :index
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :songs, dependent: :destroy

  validates :name, presence: true, length: {maximum: 50}
end

app/controllers/admins/genres_controller.rb
class Admins::GenresController < ApplicationController
  load_and_authorize_resource

  def index
    @genres = Genre.all.order created_at: :desc
    @genre = Genre.new
  end

  def create
    @genre = Genre.new genre_params
    if @genre.save
      respond_to do |format|
        format.html{redirect_to admins_genres_path}
        format.js
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @genre.update_attributes genre_params
      respond_to do |format|
        format.js
      end
    else
      flash[:danger] = t "flash.danger.cannot_update"
      redirect_to admins_genres_path
    end
  end

  def destroy
    if @genre.destroy
      respond_to do |format|
        format.js
      end
    else
      flash[:danger] = t "flash.danger.not_deleted"
      redirect_to admins_genres_path
    end
  end

  private
  def genre_params
    params.require(:genre).permit :name
  end
end

app/views/admins/genres/_form.html.erb
<%= form_for [:admins, @genre], html: {method: :put}, remote: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="col-md-9">
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="col-md-3">
    <%= f.submit t("genres.update"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admins/genres/_genre.html.erb
<li id="genre-<%= genre.id %>">
  <div class="col-md-8">
    <%= genre.name %>
  </div>
  <div class="col-md-4">
    <%= link_to edit_admins_genre_path(genre), remote: true do %>
      <i class="fa fa-pencil-square-o"></i>
      <%= t "edit" %>
    <% end %> |
    <%= link_to admins_genre_path(genre), method: :delete, remote: true,
      data: {confirm: t("confirm")} do %>
      <i class="fa fa-trash-o"></i>
      <%= t "delete" %>
    <% end %>
  </div>
</li>

app/views/admins/genres/create.js.erb
$('#genres ol').prepend('<%= j render @genre %>');
$('#genre_name').val('');

app/views/admins/genres/destroy.js.erb
$('#genre-<%= @genre.id %>').slideUp();

app/views/admins/genres/edit.js.erb
$('#genre-<%= @genre.id %>').html('<%= j render "admins/genres/form" %>');

app/views/admins/genres/index.html.erb
<div class="container">
  <div class="col-md-12">
    <h2><%= t "category" %></h2>
    <div class="col-md-5">
      <div id="form-create">
        <%= form_for [:admins, @genre], remote: true do |f| %>
          <%= f.label :name %><br>
          <%= f.text_field :name, class: "form-control"  %>
          <%= f.submit t("genres.create"), class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div class="col-md-7" id="genres">
      <ol class="genres">
        <%= render @genres %>
      </ol>
    </div>
  </div>
</div>

app/views/admins/genres/update.js.erb
$('#genre-<%= @genre.id %>').replaceWith('<%= j render @genre %>');