config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  resources :users, only: [:index, :show] do
    resources :relationships, only: :index
  end
  resources :songs
  resources :comments, except: [:index, :new, :show]
  resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reports, only: [:new, :create]

  namespace :admins do
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :destroy]
    resources :reports, only: :index
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :song
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  load_and_authorize_resource only: :destroy

  def create
    @song = Song.find_by id: params[:song_id]
    current_user.likes.create song: @song
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @song = @like.song
    @like.destroy
    respond_to do |format|
      format.js
    end
  end
end

app/views/likes/_like_form.html.erb
<% if current_user.like song %>
  <%= link_to like_path(current_user.like(song)),
    method: :delete, remote: true, class: "btn btn-danger" do %>
    <i class="fa fa-heartbeat" aria-hidden="true"> <%= t "song.unlike" %> </i>
  <% end %>
<% else %>
  <%= link_to likes_path(song_id: song.id),
    method: :post, remote: true, class: "btn btn-default" do %>
    <i class="fa fa-heart-o" aria-hidden="true"> <%= t "song.like" %></i>
  <% end %>
<% end %>
<span class="btn btn-default disabled">
  <%= song.likes.count %>
</span>

app/views/likes/create.js.erb
$('.like-book').html('<%= j render "likes/like_form", song: @song %>');

app/views/likes/destroy.js.erb
$('.like-book').html('<%= j render "likes/like_form", song: @song %>');