config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  resources :users, only: [:index, :show] do
    resources :relationships, only: :index
  end
  resources :songs
  resources :comments, except: [:index, :new, :show]
  resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reports, only: [:new, :create]

  namespace :admins do
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :destroy]
    resources :reports, only: :index
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :user
  belongs_to :genre

  has_many :ratings, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy

  mount_uploader :audio, AudioUploader

  validates :title, presence: true
  validates :artist, presence: true
  validates :genre, presence: true

  scope :search_song, -> search_param do
    where "title LIKE ? OR artist LIKE ?",
      "%#{search_param}%", "%#{search_param}%" if search_param.present?
  end

  scope :feeds, -> id {where("user_id IN
    (SELECT followed_id FROM relationships WHERE follower_id = :user_id)
    OR user_id = :user_id", user_id: id)}
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  load_and_authorize_resource
  before_action :load_genres, only: [:new, :edit]

  def index
    search_song = Song.search_song(params[:search_param])
      .order created_at: :desc
    @songs = search_song.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @song = Song.new
  end

  def create
    @song = current_user.songs.new song_params
    if @song.save
      flash[:info] = t "flash.info.upload_song_success"
      redirect_to current_user
    else
      load_genres
      render :new
    end
  end

  def show
    @comment = Comment.new
    @report = Report.new
    views_song
  end

  def edit
  end

  def update
    if @song.update_attributes song_params
      flash[:success] = t "flash.success.updated"
      redirect_to @song
    else
      load_genres
      render :edit
      flash[:danger] = t "flash.danger.not_updated"
    end
  end

  def destroy
    if @song.destroy
      flash[:success] = t "flash.success.deleted"
    else
      flash[:danger] = t "flash.danger.not_deleted"
    end
    redirect_to current_user
  end

  private
  def song_params
    params.require(:song).permit :title, :artist, :description,
      :audio, :genre_id
  end

  def load_genres
    @genres = Genre.all
  end

  def views_song
    @song.update_attributes views: (@song.views + 1)
  end
end

app/views/songs/_form.html.erb
<%= form_for @song do |f| %>
  <%= render "shared/error_messages", object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :artist %>
  <%= f.text_field :artist, class: "form-control" %>

  <%= f.label :genre %>
  <%= f.select :genre_id, @genres.collect{|key| [key.name, key.id]},
    {include_blank: t("song.new.select")}, {class: "form-control"} %>
  <br>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.file_field :audio %>
  <br>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/songs/_song.html.erb
<li>
  <h4><%= link_to song.title, song %></h4>
  <h5><%= song.artist %></h5>
  <%= t "song.show.uploader" %> <%= song.user.name %><br>
  <%= t "song.show.genre" %> <%= song.genre.name %><br>
  <i class="fa fa-heart"> <%= song.likes.count %></i> |
  <i class="fa fa-headphones"> <%= song.views %></i>
</li>

app/views/songs/edit.html.erb
<% provide :button_text, t("song.edit_button") %>

<h1><%= t "song.edit" %></h1>

<div class="col-md-6 col-md-offset-3">
  <%= render "form" %>
</div>

app/views/songs/index.html.erb
<div class="container">
  <h1><%= t "song.all" %></h1>

  <div class="search col-md-12">
    <div class="col-md-6 col-md-offset-3">
      <%= form_tag songs_path, method: :get, remote: true do %>
        <div class="col-md-8">
          <%= text_field_tag :search_param, params[:search_param],
            placeholder: t("song.search"), class: "form-control" %>
        </div>
        <div class="col-md-4">
          <%= submit_tag t("search"), name: nil, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-8 col-md-offset-2">
    <ol class="songs song-index">
      <%= render @songs %>
    </ol>
     <%= will_paginate %>
  </div>
</div>

app/views/songs/index.js.erb
$('.song-index').html('<%= j render @songs %>');

app/views/songs/new.html.erb
<% provide :button_text, t("song.new.button") %>

<h1><%= t "song.new.upload" %></h1>

<div class="col-md-6 col-md-offset-3">
  <%= render "form" %>
</div>

app/views/songs/show.html.erb
<div class="col-md-12">
  <div class="col-md-8">
    <div class="col-md-9">
      <h3><%= @song.title %></h3>
    </div>
    <div class="col-md-3">
      <% if can? :update, @song %>
        <%= link_to t("edit"), edit_song_path(@song), class: "btn btn-success" %>
      <% end %>
      <% if can? :destroy, @song %>
        <%= link_to t("delete"), song_path(@song), method: :delete,
          data: {confirm: t("confirm")}, class: "btn btn-danger" %>
      <% end %>
      <% if !current_user.is_admin && !current_user.current_user?(@song.user) %>
        <%= link_to t("report"), "#", {remote: true, "data-toggle":  "modal",
          "data-target": "#modal-report", class: "btn btn-warning"} %>
        </i>
      <% end %>
    </div>

    <div class="modal fade" id="modal-report" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
              &times;
            </button>
            <h4 class="modal-title"><%= t "report" %></h4>
          </div>
          <div class="modal-body">
            <%= form_for @report, html: {method: :post} do |f| %>
              <%= f.hidden_field :song_id, value: @song.id %>
              <%= f.hidden_field :user_id, value: current_user.id %>

              <%= f.label :description %>
              <%= f.text_area :description, class: "form-control" %>
              <%= f.submit t("report_new.button"), class: "btn btn-primary" %>
            <% end %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">
              <%= t "close" %>
            </button>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <h4><%= @song.artist %></h4><br>
      <%= t "song.show.uploader" %>
      <%= link_to @song.user.name, @song.user %><br>
      <%= t "song.show.genre" %> <%= @song.genre.name %><br>
      <br>

      <span class="like-book">
        <%= render "likes/like_form", song: @song %>
      </span>
      <h3><span class="label label-info label-lg">
        <i class="fa fa-headphones"> | <%= @song.views %></i>
      </span></h3>

      <div class="panel panel-default">
        <div class="audio-bg">
          <div class="audio-player">
            <%= audio_tag @song.audio, type: "audio/mp3",
              controls: "controls", id: "audio-player" %>
          </div>
        </div>
      </div>
      <br>

      <% if @song.comments %>
        <h4><%= t "comment.name", count: @song.comments.count %></h4>
      <% end %>

      <div class="col-md-12 comment-form">
        <%= form_for @comment, url: comments_path, html: {method: :post},
          remote: true do |f| %>
          <%= render "shared/error_messages", object: f.object %>
          <%= f.hidden_field :song_id, value: @song.id %>
          <div class="col-md-10">
            <%= f.text_area :content, class: "form-control" %>
          </div>
          <div class="col-md-2">
            <%= f.submit t("comment.button"), class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>

      <div id="comments">
        <%= render @song.comments %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <br>
    <div class="panel panel-primary">
      <div class="panel-heading"><%= t "song.recommend" %></div>
      <div class="panel-body">
        <ol class="songs">
          <% @song.user.songs.shuffle[0..4].each do |song| %>
            <li>
              <%= link_to song.title, song %>
              <br>
              <%= song.user.name %>
            </li>
          <% end %>
        </ol>
      </div>
    </div>
  </div>
</div>