config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"

  get "/signin", to: "sessions#new"
  post "/signin", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  resources :users, only: [:index, :show] do
    resources :relationships, only: :index
  end
  resources :songs
  resources :comments, except: [:index, :new, :show]
  resources :likes, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :reports, only: [:new, :create]

  namespace :admins do
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :destroy]
    resources :reports, only: :index
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("name"), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to t("home"), root_path %></li>
          <% if current_user.is_admin? %>
            <li><%= link_to t("genres.name"), admins_genres_path %></li>
            <li><%= link_to t("page.home.user"), admins_users_path %></li>
            <li><%= link_to t("page.home.report"), admins_reports_path %></li>
          <% else %>
            <li><%= link_to t("page.home.upload"), new_song_path %></li>
            <li><%= link_to t("page.home.user"), users_path %></li>
          <% end %>
          <li><%= link_to t("page.home.song"), songs_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t "page.home.account" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("page.home.profile"), current_user %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t("page.home.signout"), destroy_user_session_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("page.home.signin"), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application",
      "data-turbolinks-track": true %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
  </body>
</html>